config/routes.rb
Rails.application.routes.draw do


  resources :places, :path => "london"
  resources :leads
  #resources :charges
  root to: 'places#index'
  get 'about' => 'places#about'
  post 'places/subscribe' => 'places#subscribe'
  #get 'london/about' => 'places#about'
  #root :to => redirect('/london')
  # get 'placelist' => 'places#list'
end

app/models/lead.rb
class Lead < ActiveRecord::Base
	validates :email, presence: true
end

app/models/place.rb
class Place < ActiveRecord::Base
	#Get rid of the /places/2 url
	extend FriendlyId
  	friendly_id :name, use: :slugged

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

	def new
	end

	def about
	end

	def create
	  # Amount in cents
	  @amount = 500

	  customer = Stripe::Customer.create(
	    :email => 'example@stripe.com',
	    :card  => params[:stripeToken]
	  )

	  charge = Stripe::Charge.create(
	    :customer    => customer.id,
	    :amount      => @amount,
	    :description => 'Rails Stripe customer',
	    :currency    => 'usd'
	  )

	rescue Stripe::CardError => e
	  flash[:error] = e.message
	  redirect_to charges_path
	end
	
end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController
	def create
		@lead = Lead.new(lead_params)

		@list_id = 'c5baa21607'
		gb = Gibbon::API.new
		logger.debug @lead_email

		    response = gb.lists.subscribe({
		      :id => @list_id,
		      :email => {:email => @lead.email},
		      :double_optin => false
		      })

		    puts response

		respond_to do |format|

			if @lead.save
				format.html{redirect_to root_path, notice: "Saved successfully!"}
				format.js
				#format.json { render json: @lead }
			else
				format.html{redirect_to root_path, alert: "Failed to save"}
				format.js
				#format.json { render json: @lead.errors.full_messages, status: :unprocessable_entity }
			end
		end
	end

	private

	def lead_params
		params.require(:lead).permit(:email)
	end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  # GET /places
  # GET /places.json
  def about
  end
  
  def list
    @places = Place.all.order("rating DESC")
  end

  def index
    @lead = Lead.new
    @places = Place.all.order("rating DESC")
  end

  def subscribe
    @lead = Lead.new(lead_params) 
    respond_to do |format|

        if @lead.save
          format.html{redirect_to root_path, notice: "Saved successfully!"}
          format.js
        else
          format.html{redirect_to root_path, alert: "Failed to save"}
          format.js
        end
    end

    @lead._status

  end

  # GET /places/1
  # GET /places/1.json
  def show
    @place = Place.friendly.find(params[:id])

    respond_to do |format|
      format.html { } # show.html.erb
      format.json { render json: @place }
    end
  end

  def new
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      #params.require(:place).permit(:name, :description, :rating, :geo_latitude, :geo_latitude, :romance)
      params.require(:place).permit!
    end

    def lead_params
    params.require(:lead).permit(:email)
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/charges/charges.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <label class="amount">
      <span>Amount: $5.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="500"
          data-locale="auto"></script>
<% end %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                 <%= link_to root_path do %>
                    <div class="navbar-brand page-scroll">Where To Take Your Date <span style="font-weight:200;" class="hidden-xs"> - London</span></div>
                <% end %>

            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                <li>
                <p class="navbar-btn" style="padding:0px;">
                    <a style="margin-top:2px;"class="typeform-share btn btn-primary outline" href="https://plaksel.typeform.com/to/fh6aEj" data-mode="1" target="_blank">Suggest Venue</a>
                    <script>(function(){var qs,js,q,s,d=document,gi=d.getElementById,ce=d.createElement,gt=d.getElementsByTagName,id='typef_orm',b='https://s3-eu-west-1.amazonaws.com/share.typeform.com/';if(!gi.call(d,id)){js=ce.call(d,'script');js.id=id;js.src=b+'share.js';q=gt.call(d,'script')[0];q.parentNode.insertBefore(js,q)}id=id+'_';if(!gi.call(d,id)){qs=ce.call(d,'link');qs.rel='stylesheet';qs.id=id;qs.href=b+'share-button.css';s=gt.call(d,'head')[0];s.appendChild(qs,s)}})()</script>
                </p>
                </li>
                  <li><%= link_to "About", about_path %></li>                  
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
	<title><%= content_for?(:title) ? yield(:title) : "Where To Take Your Date - London" %></title>
	<meta name="description" content="<%= content_for?(:description) ? yield(:description) : "You finally got your date sorted, but you don't know where to go? Where to take your date brings you the best dating spots in London!" %>">
	<script type="text/javascript" src="//cdn.bounce.bar/115220.js"></script>
	<script src="https://cdn.optimizely.com/js/5373461882.js"></script>
	<%= stylesheet_link_tag 'application', media: 'all' %>
	<%= javascript_include_tag 'application'%>
	<%= csrf_meta_tags %>
	<link rel="image_src" href="<%=image_path("social-img.jpg")%>" />
	<meta name="google-site-verification" content="ZWgmehue9VtV3KE9IkF2SACjcEpBZoQNXzjzEFrh4Qg" />
	<%= favicon_link_tag 'favicon-02.ico' %>
	<%= yield %>

</body>
</html>

app/views/leads/create.js.erb
$('#successMessage').empty();

<%if @lead.errors.any? %>
	$('#successMessage').append("<p>Please enter a valid email address</p>");
<% else %>
	$('#new_lead').hide();
	$('#successMessage').append("<p>Thanks for joining!</p>");
	$('#successMessage').removeClass('pull-left');
<%end%>

app/views/places/_list.html.erb
<div class="container" style="padding-left:0px;">
  <div class="row row-centered grid" style="margin:0 auto;">
    <% @places.each_with_index do |place, idx| %>
    <div class="venue col-xs-6 col-centered2 col-fixed grid-item <%=place.dateType%> <%= place.drinksOrFood%>" data-postcode="<%=place.postcode%>" data-chancetotalk="<%=place.changeToTalk%>" data-price="<%=place.price%>" data-impress="<%=place.impressed%>" data-romance="<%=place.romance%>" style="">
      <div class="itemAlign effect-chico" id="postcodeFilter" data-link="<%= place_path(place) %>" style="">
        <%= link_to place_path(place) do %>
        <img class="lazy" data-src="<%=place.imageUrl%>" src="" alt="<%=place.name%>"/>

        <div class="shag"><p><i class="fa fa-heart-o"></i> <%=place.rating%>%</p></div>
        <div class="informationBox">
          <h2><%= place.name.titleize %></h2>
          <p>
            <span class="" style="padding-right:10px;"><i class="iconInformationBox fa fa-glass"></i> <%=place.typePlace%></span>
            <span class="" style="padding-right:10px;"><i class="iconInformationBox fa fa-lg fa-map-marker"></i> <%=place.postcode%></span> 
            <span class=" priceID" data-price="<%=place.price%>"></span>
          </p>
        </div>  
        <% end %>
      </div><!--itemAlign--> 
    </div><!--col-->
    <%# if((idx+1) % 6 == 0)%>
      <!-- <div class="row" style="width:100%; background-color:green; margin:0px; padding:0px;">
        <div class="col-md-12 text-center" id="">
          <h2>Your ad here? Get in contact now!</h2>
         </div> --> <!--col-md-11-->
       <!-- </div> --><!-- nested row-->
    <%# end %>
    <% end %>
  </div><!--row centered-->
</div><!-- container-->

app/views/places/about.html.erb
  </head>
  <body id="" class="<%= controller_name %> <%= action_name %>">
    <main role="main">
      <%= render 'layouts/messages' %>
    </main>

    <%= render 'layouts/navigation' %>  <section class="bg-show" id="">
  	<div class="row">
  		<div class="col-md-8 col-md-offset-2 about" style="">
  		<h1>The Story behind</h1>
      <p>Two years ago I got relocated to London due to my work for TomTom, a chance I was happy to take. In one of the world's most vibrant cities it was easy to adjust: meeting new friends, finding a new home and discovering new places. After all, a city like London has much to offer.<br><br>

      Then, I got a date. <br><br>

      Finding a suitable place to take your first date should be the least of your problems. However, at that time I felt like the city had turned against me; even the most logical source of knowledge (the internet) couldn't help me out. After complaining to my friends, it turned out that I had been searching in the wrong place; they were happy to assist me with a list of restaurants, bars and other places they had taken their dates to. Big thanks to <a href="https://nl.linkedin.com/in/joostroes" target="_blank" style="font-weight:bold;">Joost</a> and <a href="https://uk.linkedin.com/in/frankdj" target="_blank" style="font-weight:bold;">Frank</a> and Excel sheet was born. <br><br>

      Every time one of us went on a date we updated the list and even started rating places on so many different variables. More friends came to know about our list and then it clicked me: “why not share this with the world?” and so <span style="color:#f05f40; font-weight:700;">Where To Take Your Date</span> was born. <br><br>

      <span style="color:#f05f40; font-weight:700;">Where To Take Your Date</span> is the list of all good places you can take your date to, and is in essence still what it started as: an advice from man to man, from friend to friend, rated by a ‘fellow bro’. The places which were not good enough didn’t make it to the list, obviously. It is not called Disaster Dates. <br><br>

      I bootstrapped the website in just a few weekends and evenings, fuelled by many coffees. The main goal was to get something out of the door as quickly as possible and check whether people actually want something like this. I often see startups, even entire development and design teams spending a tremendous amount of time on a new feature, however once shipped only a few people use it. Developing something new is one thing, delivering and actually launching is a completely different story. <br><br>

      The short amount of time and limited resources forced me to focus on only the most important features. Being able to making decisions carefully yet quickly considering multiple perspectives. and launch as quickly as possible. Most of <span style="color:#f05f40; font-weight:700;">Where To Take Your Date</span> is automated, so it will not require much maintenance in near future. That will give me more time to focus on the next big step: <span style="color:#f05f40; font-weight:700;">Growth.</span><br><br>

      As <span style="color:#f05f40; font-weight:700;">Where To Take Your Date</span> is in this very early stage I am very open to new ideas and suggestions that would improve or monetise the website. Send me a tweet, drop me message, and let’s take it from there.
      <br><br></p>

        <div class="col-md-4 col-md-offset-4">
          <%= image_tag("rikvandonselaar_small.jpg", :alt => "Rik van Donselaar", :class => "img-circle", :style => "display:inline-block;") %>
          <a href="https://twitter.com/rikvandonselaar" target="_blank" style="margin:0 auto; font-weight:bold;">@RikvanDonselaar</a></p>
        </div>
      </div><!--col md 8 -->
    </div> <!--row-->
  </section>
  <div class='creater'>
  <a class="btn btn-default" href="https://www.facebook.com/wheretotakeyourdate?_rdr=p" role="button" style="background-color:#3B5998;" target="_blank"><i class="fa fa-lg fa-facebook" style="color:white;"></i></a>
  <a class="btn btn-default" href="https://twitter.com/WTTYD" role="button" style="background-color:#4099FF;" target="_blank"><i class="fa fa-lg fa-twitter" style="color:white;"></i></a>
  <a class="btn btn-default" href="https://instagram.com/wheretotakeyourdate/" role="button" style="background-color:#125688;" target="_blank"><i class="fa fa-lg fa-instagram" style="color:white;"></i></a>
</div>

app/views/places/list.html.erb
<%= render 'list' %>